<#import "/__wrapper.ftlh" as wrapper>
<@wrapper.main>
<div class="row">
	<div class="col-md-12">
		<h1>テストログイン成功 </h1>
	</div>
	<div class="col-md-12">
		<a href="/admin/taxonomy">タクソノミー管理</a><br />
		<a href="/admin/term">ターム管理</a><br />
		<a href="/admin/termtree">タクソノミー階層管理</a><br />
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<a href="/logout">ログアウト</a>
	</div>
</div>
</@wrapper.main>